# Numpy Functions 

## Importing (Keys and Import)

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install --upgrade pip

     |████████████████████████████████| 1.5 MB 10.0 MB/s eta 0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
pip install --upgrade ipython jupyter

     |████████████████████████████████| 118 kB 22.0 MB/s eta 0:00:01
     |████████████████████████████████| 54 kB 5.3 MB/s  eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


## Creating Arrays

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#1-D array#
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [13]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [14]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [15]:
np.random.rand(4,5)

array([[0.57938321, 0.8474248 , 0.70904782, 0.57960128, 0.96211285],
       [0.27670789, 0.66597071, 0.53013499, 0.29285675, 0.97212108],
       [0.28453737, 0.49808822, 0.48582037, 0.51509803, 0.68469493],
       [0.51688776, 0.33902897, 0.32820428, 0.7633514 , 0.07440796]])

In [16]:
np.random.rand(6,7)*100

array([[64.78565347, 98.19260187, 35.3237239 , 58.30433029, 82.55216552,
        19.80436404, 61.65432638],
       [54.36601901, 96.62134765, 94.53997859, 49.8841125 , 85.37500028,
        33.37098606, 49.33855576],
       [87.56492444, 79.5609673 , 95.71104132,  7.24192102,  4.89629977,
        18.28974912, 25.91055962],
       [73.89241806, 76.67702061, 14.41239177,  2.66179751, 21.17563895,
        99.00200367, 27.40345573],
       [27.95714877, 45.01403431, 80.64137578, 16.42210902, 61.01876775,
        32.19422245, 44.41278374],
       [92.96071932, 51.84440408,  8.16632749, 57.24283655, 39.02823302,
        89.0108843 , 55.21007932]])

In [17]:
np.random.randint(5,size=(2,3))

array([[2, 4, 3],
       [1, 1, 3]])

## Inspecting Properties

In [23]:
arr1 = [1,2,3,4,5,6,7,8]
nums = np.array ([1,2,3,4,5,6,7,8])
type(nums)

numpy.ndarray

In [24]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#Array Size#
arr1.size

10

In [26]:
#Array Shape#
arr1.shape

(10,)

In [27]:
#Array Type#
arr1.dtype

dtype('int64')

In [29]:
#Array Type#
arr.astype

<function ndarray.astype>

In [30]:
#Array tolist#
arr1.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

In [32]:
#d-type parameters#
arr2 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = complex)
arr2

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [33]:
#n-dimension#
arr1 = np.array([(1,2,3,4),(5,6,7,8)])
arr1.ndim

2

## Dimensions

In [34]:
#1-Dimesion#
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [42]:
#2-Dimension#
arr3 = np.arange(10).reshape
arr3

<function ndarray.reshape>

In [43]:
#3-Dimension#
arr4 = np.arange(24).reshape(2,3,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
#Multi-dimensions#
arr5 = np.array([(1,2,3),(4,5,6)])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
#n-dimension#
arr1 = np.array([(1,2,3,4),(5,6,7,8)])
arr1.ndim

2

In [52]:
#Minimum-Dimensions#
arr6 = np.array([0,1,2,3,4,5,6,7,8,9,10],ndmin = 2)
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [85]:
#2-Dimension zero matrix#
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

## Copying / Sorting / Reshaping

In [54]:
#Copy array#
np.copy(arr1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
#View array#
arr1.view('int64')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
#Sort array#
arr1.sort()

In [61]:
arr1.sort(axis=0)

In [64]:
#Transpose of Array#
arr1.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Adding / Removing /Indexing elements

In [76]:
#Inserting values#
np.insert(arr1,8,[9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
#Indexing values#
arr7 = np.array([1,2,3,4,5,6,7,8])
arr7[[0,1]]

array([1, 2])

In [84]:
#Identity matrix#
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Combining / Splitting

In [87]:
#Concatenating arrays (axis=0)#
arr1 = [0,1,2,3,4]
arr2 = [5,6,7,8,9]
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
#Concatenating arrays (axis=1)#
arr3 = ([(1,2,3),(4,5,6)])
arr4 = ([(5,6,7),(8,9,10)])
arr = np.concatenate((arr3,arr4),axis=1)
arr

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10]])

In [97]:
#Splitting array#
np.array_split(arr1,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [100]:
#Horizontal splitting array#
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.hsplit(arr, 3)
new_arr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

## Indexing / Slicing / Subsetting

In [101]:
arr[5]

array([16, 17, 18])

In [104]:
arr[1] = 4

In [107]:
#Indexing#
arr = np.array([1,2,3,4,5,6,7,8])
arr[[0,1]]

array([1, 2])

In [108]:
#log-space array#
arr = np.logspace(3,8,num=10,base=1000.0,dtype=float)
arr

array([1.00000000e+09, 4.64158883e+10, 2.15443469e+12, 1.00000000e+14,
       4.64158883e+15, 2.15443469e+17, 1.00000000e+19, 4.64158883e+20,
       2.15443469e+22, 1.00000000e+24])

In [109]:
#Diagonal Array#
np.diag(np.arange(0,8,1))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

In [113]:
np.diag(np.diag(np.arange(12).reshape((4,3))))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [114]:
#Vertical stack#
arr1 = np.array([(1,2,3,4),(5,6,7,8)])
arr2 = np.array([(9,10,11,12),(13,14,15,16)])
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
#Horizontal stack#
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [116]:
#Linear spacing#
arr = np.linspace(1,3,10)
print(arr)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [118]:
#Slicing#
arr = np.array([(1,2,3,4),(5,6,7,8)])
print(arr[0:,1])

[2 6]


In [146]:
#Slicing in multi-dimension#
arr = np.array([(2,3),(4,5),(7,8)])
arr[0:2,1]

array([3, 5])

In [123]:
(arr1<3)&(arr2>5)

array([[ True,  True, False, False],
       [False, False, False, False]])

In [125]:
~arr2

array([[-10, -11, -12, -13],
       [-14, -15, -16, -17]])

In [127]:
arr2[arr2<5]

array([], dtype=int64)

In [128]:
#Boolean Method#
bool_arr = np.array([1,.5,0,'aa',''],dtype=bool)
print(bool_arr)

[ True  True False  True False]


In [129]:
#Filtering values (odd number)#
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [130]:
#Generating Random Number#
np.random.rand(3,3)


array([[0.05662056, 0.18039519, 0.11988842],
       [0.35490384, 0.99262524, 0.23466825],
       [0.21480585, 0.57141225, 0.49170164]])

In [131]:
#Random number in a given range#
np.random.randint(2,size=5)

array([1, 1, 1, 1, 0])

In [132]:
np.random.randint(15,size=(2,3))

array([[10,  9,  8],
       [ 4, 13,  1]])

In [133]:
#last value#
arr1[-1]

array([5, 6, 7, 8])

## Scalar Maths

In [134]:
#Adding value#
np.add(arr1,1)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [136]:
#Adding in matrix#
arr2 = np.array([(1,2,3),(4,5,6)])
arr3 = np.array([(7,8,9),(10,11,12)])
arr2+arr3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [137]:
#Subtracting value#
np.subtract(arr1,2)

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [138]:
#Subtracting in matrix#
arr2-arr3

array([[-6, -6, -6],
       [-6, -6, -6]])

In [139]:
#Multiplying value#
np.multiply(arr1,3)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [140]:
#Multiplying in matrix#
arr2*arr3

array([[ 7, 16, 27],
       [40, 55, 72]])

In [141]:
#Dividing value#
np.divide(arr1,4)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [142]:
#Dividing in matrix#
arr2/arr3

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [143]:
#Squareroot#
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [144]:
#Minimum values#
arr1.min()

1

In [145]:
#Maximum values#
arr1.max()

6

In [147]:
#Power#
np.power(arr2,5)

array([[   1,   32,  243],
       [1024, 3125, 7776]])

## Vector Maths

In [148]:
#Adding#
np.add(arr2,arr3)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [150]:
#Subtracting#
np.subtract(arr2,arr3)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [151]:
#Multiplying#
np.multiply(arr2,arr3)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [152]:
#Dividing#
np.divide(arr2,arr3)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [153]:
#Power#
np.power(arr2,arr3)

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [154]:
#Checking (equal or not)#
np.array_equal(arr2,arr3)

False

In [156]:
#Square-root#
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [157]:
# *Trignometric Functions* #
#Sin#
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [158]:
#Cos#
np.cos(arr2)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [159]:
#Tan#
np.tan(arr3)

array([[   0.87144798,   -6.79971146,   -0.45231566],
       [   0.64836083, -225.95084645,   -0.63585993]])

In [160]:
#Logarithm#
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [161]:
#Exponential#
np.exp(arr2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [162]:
#Absolute value#
np.abs(arr3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [163]:
#Ceiling value#
np.ceil(arr1)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [164]:
#Floor value#
np.floor(arr2)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [165]:
#Round-off value#
np.round(arr3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [166]:
#Reciprocal#
np.reciprocal(arr1)

array([[1, 0, 0],
       [0, 0, 0]])

In [167]:
#Remainder#
np.remainder((arr2),3)

array([[1, 2, 0],
       [1, 2, 0]])

In [168]:
#Sign#
np.sign(arr1)

array([[1, 1, 1],
       [1, 1, 1]])

## Statistics

In [169]:
#Mean value#
np.mean(arr2,axis=0)

array([2.5, 3.5, 4.5])

In [170]:
arr2.sum()

21

In [171]:
#Minimum value#
arr.min()

2

In [172]:
#Maximum value (axis=0)#
arr.max(axis=0)

array([7, 8])

In [173]:
#Variance#
np.var(arr2)

2.9166666666666665

In [174]:
#Standard deviation#
np.std(arr2,axis=1)

array([0.81649658, 0.81649658])

In [178]:
#Coefficient of Corelation#
np.corrcoef(arr2)

array([[1., 1.],
       [1., 1.]])